# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=512)),
                ('speelsterkte', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spel_nummer', models.IntegerField()),
                ('score', models.IntegerField()),
                ('speler1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches1', to='tennis.Speler')),
                ('speler2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches2', to='tennis.Speler')),
            ],
        ),
    ]
