# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0002_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='spel_nummer',
        ),
        migrations.AlterField(
            model_name='team',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
