# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0003_auto_20160515_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='match',
            name='kindermatch',
            field=models.BooleanField(default=False),
        ),
    ]
