# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0004_auto_20160515_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='klaar',
            field=models.BooleanField(default=False),
        ),
    ]
